//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Log.
        /// </summary>
        internal static string AuditLog {
            get {
                return ResourceManager.GetString("AuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail.
        /// </summary>
        internal static string AuditTrail {
            get {
                return ResourceManager.GetString("AuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an account to manage.
        /// </summary>
        internal static string ChooseAccountToManage {
            get {
                return ResourceManager.GetString("ChooseAccountToManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Module.
        /// </summary>
        internal static string ClaimListing {
            get {
                return ResourceManager.GetString("ClaimListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        internal static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Holder.
        /// </summary>
        internal static string ContractHolder {
            get {
                return ResourceManager.GetString("ContractHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract No.
        /// </summary>
        internal static string ContractNo {
            get {
                return ResourceManager.GetString("ContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract/Policy.
        /// </summary>
        internal static string ContractPolicy {
            get {
                return ResourceManager.GetString("ContractPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string CreateUsers {
            get {
                return ResourceManager.GetString("CreateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download QC Listing.
        /// </summary>
        internal static string DownloadQCListing {
            get {
                return ResourceManager.GetString("DownloadQCListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the One-Time Code sent to your registered email..
        /// </summary>
        internal static string FACode {
            get {
                return ResourceManager.GetString("FACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered is incorrect. Please input the correct code.
        /// </summary>
        internal static string FACodeErrorMsg {
            get {
                return ResourceManager.GetString("FACodeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One-Time Code had been Resent to your registered email at .
        /// </summary>
        internal static string FACodeResend {
            get {
                return ResourceManager.GetString("FACodeResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One-Time Code had been Sent to your registered email at.
        /// </summary>
        internal static string FACodesend {
            get {
                return ResourceManager.GetString("FACodesend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered is expired. Please click on the resend to get the new code..
        /// </summary>
        internal static string FACodeTimeOutErrorMsg {
            get {
                return ResourceManager.GetString("FACodeTimeOutErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input The Correct OTP Code..
        /// </summary>
        internal static string FACodeWrongOTPMsg {
            get {
                return ResourceManager.GetString("FACodeWrongOTPMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot username/ password.
        /// </summary>
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of this system is restricted to individuals and activities authorized by the management of the
        /// Etiqa Insurance &amp; Takaful. Unauthorized use may result in the appropriate disciplinary action and/or
        /// legal prosecution.
        /// </summary>
        internal static string ImportantNote {
            get {
                return ResourceManager.GetString("ImportantNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Note.
        /// </summary>
        internal static string ImportantNoteTitle {
            get {
                return ResourceManager.GetString("ImportantNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password you entered isn&apos;t correct. Try entering it again..
        /// </summary>
        internal static string LoginErrorMsg {
            get {
                return ResourceManager.GetString("LoginErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope you have a great experience with us!.
        /// </summary>
        internal static string LoginGreeting {
            get {
                return ResourceManager.GetString("LoginGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        internal static string LoginPageGreeting {
            get {
                return ResourceManager.GetString("LoginPageGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        internal static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malay.
        /// </summary>
        internal static string Malay {
            get {
                return ResourceManager.GetString("Malay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Access.
        /// </summary>
        internal static string ManageAccess {
            get {
                return ResourceManager.GetString("ManageAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Account.
        /// </summary>
        internal static string MasterAccount {
            get {
                return ResourceManager.GetString("MasterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Movement.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Listing.
        /// </summary>
        internal static string MemberListing {
            get {
                return ResourceManager.GetString("MemberListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period of Cover.
        /// </summary>
        internal static string PeriodOfCover {
            get {
                return ResourceManager.GetString("PeriodOfCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        internal static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Holder.
        /// </summary>
        internal static string PolicyHolder {
            get {
                return ResourceManager.GetString("PolicyHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy No.
        /// </summary>
        internal static string PolicyNo {
            get {
                return ResourceManager.GetString("PolicyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal.
        /// </summary>
        internal static string Renewal {
            get {
                return ResourceManager.GetString("Renewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Name.
        /// </summary>
        internal static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this.setCustomValidity(&quot;Please enter a valid Password&quot;).
        /// </summary>
        internal static string SetCustomValidityPassword {
            get {
                return ResourceManager.GetString("SetCustomValidityPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this.setCustomValidity(&quot;Please enter a valid UserName &quot;).
        /// </summary>
        internal static string SetCustomValidityUserName {
            get {
                return ResourceManager.GetString("SetCustomValidityUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Status.
        /// </summary>
        internal static string ShowStatus {
            get {
                return ResourceManager.GetString("ShowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit New Member/ Endorsement Listing.
        /// </summary>
        internal static string SubmitNewMember {
            get {
                return ResourceManager.GetString("SubmitNewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidiary.
        /// </summary>
        internal static string Subsidiary {
            get {
                return ResourceManager.GetString("Subsidiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Access Matrix.
        /// </summary>
        internal static string UserAccessMatrix {
            get {
                return ResourceManager.GetString("UserAccessMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        internal static string UserGuide {
            get {
                return ResourceManager.GetString("UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
