//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPP.CorporatePortal.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Users { get; set; }
        public string Description { get; set; }
        public string UserIPAddress { get; set; }
        public string Menu { get; set; }
        public string Type { get; set; }
    }
}
