//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPP.CorporatePortal.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileUpload()
        {
            this.FileUploadFallout_remove = new HashSet<FileUploadFallout_remove>();
        }
    
        public int Id { get; set; }
        public string UploadType { get; set; }
        public string CorporateId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> UploadedDateTime { get; set; }
        public string UploadedBy { get; set; }
        public string MappedFileName { get; set; }
        public string LocalPath { get; set; }
        public string DestinationPath { get; set; }
        public string Status { get; set; }
        public string CorporateSourceId { get; set; }
        public string PolicySourceId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<double> ContributionAmt { get; set; }
        public string InvoiceStatus { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> PolicyVersion { get; set; }
        public string RPAExceptionLink { get; set; }
        public string CGLSExceptionLink { get; set; }
        public string InvoiceLink { get; set; }
        public string ExceptionLink { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public byte[] InvoiceFile { get; set; }
        public byte[] ExceptionFile { get; set; }
        public byte[] UploadedFile { get; set; }
        public byte[] MappedRPAFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileUploadFallout_remove> FileUploadFallout_remove { get; set; }
    }
}
