//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPP.CorporatePortal.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public string SourceId { get; set; }
        public string ProductName { get; set; }
        public string ContractNo { get; set; }
        public string ContractHolder { get; set; }
        public Nullable<System.DateTime> PeriodOfCoverStart { get; set; }
        public Nullable<System.DateTime> PeriodOfCoverEnd { get; set; }
        public Nullable<System.DateTime> Renewal { get; set; }
        public string Status { get; set; }
        public string AgentCode { get; set; }
        public Nullable<int> Version { get; set; }
        public string ProductCode { get; set; }
        public string Entity { get; set; }
    }
}
